name: ZSlotDrop
main: io.github.yuazer.zslotdrop.Main
version: 0.6
api-version: 1.13
commands:
  zslotdrop:
    aliases:
      - zsd
    description: the command for this plugin
depend:
  - CMI
  - ProtocolLib